### ISSUE TITLE
ImportError: cannot import name Markup from flask

### ISSUE THREAD

**Issue by lavitiy** [PalisadoesFoundation/switchmap-ng#160]
Since Flask is using Jinja2 for quite some time, they removed the re-export of Markup with the 3.0.0 release

**Comment by lavitiy** [comment]
19:12 $ maintenance/install.py 
Do you want switchmap-ng to start automatically after a reboot?: (Y, N) n
OK - Python version 3.10.
OK - Python pip3 executable found.
OK - Python module "setuptools" is installed.
OK - Python pip3 executable found.
OK - Python module "PyYAML" is installed.
OK - Created configuration file /home/gramazeka/switchmap-ng/switchmap-ng/etc/config.yaml.
OK - Installing required pip3 packages from requirements.txt file.
2023-10-31 19:13:19,431962 - gramazeka - STATUS - [1127] Could not start daemon switchmap-ng-api.
2023-10-31 19:13:19,432095 - gramazeka - STATUS - [1001] Failed to start daemon switchmap-ng-api.
2023-10-31 19:13:19,972491 - gramazeka - STATUS - [1127] Could not start daemon switchmap-ng-poller.
2023-10-31 19:13:19,972631 - gramazeka - STATUS - [1001] Failed to start daemon switchmap-ng-poller.
********************************************************************************
1) Edit file /home/gramazeka/switchmap-ng/switchmap-ng/etc/config.yaml with correct SNMP parameters and then restart the daemons.
2) You can restart switchmap-ng daemons with these commands:
   $ bin/switchmap-ng-cil restart api
   $ bin/switchmap-ng-cli restart poller
3) Switchmap-NG will not automatically restart after a reboot. You need to re-install as the "root" user for this to occur.

19:28 $ bin/switchmap-ng-cli restart poller
Traceback (most recent call last):
  File "/home/gramazeka/switchmap-ng/switchmap-ng/bin/switchmap-ng-cli", line 24, in <module>
    from switchmap.cli import cli
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/cli/cli.py", line 15, in <module>
    from switchmap.cli import show, start, test, stop, restart
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/cli/show.py", line 16, in <module>
    from switchmap.main.agent import Agent, AgentAPI, AgentDaemon
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/main/agent.py", line 29, in <module>
    from switchmap.www import API
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/www/__init__.py", line 14, in <module>
    from switchmap.www.routes.api.devices import API_DEVICES
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/www/routes/api/devices.py", line 12, in <module>
    from switchmap.www.pages import device
  File "/home/gramazeka/switchmap-ng/switchmap-ng/switchmap/www/pages/device.py", line 10, in <module>
    from flask_table import Table, Col
  File "/home/gramazeka/.local/lib/python3.10/site-packages/flask_table/__init__.py", line 1, in <module>
    from .table import Table, create_table
  File "/home/gramazeka/.local/lib/python3.10/site-packages/flask_table/table.py", line 5, in <module>
    from flask import Markup
**ImportError: cannot import name 'Markup' from 'flask' (/home/gramazeka/.local/lib/python3.10/site-packages/flask/__init__.py)**

19:25 $ uname -a
Linux-VirtualBox 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
19:25 $ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

**Comment by maxferrario-msf** [comment]
I have the same error, and the same OS (Ubuntu 22.04.3 LTS).
The only (minor?) difference is that in my case the error message refers to the file lib/python3.10/dist-packages/flask/**__init__.py**

**Comment by aakarshgopishetty** [comment]
Hi! I’d like to work on resolving the issue where Markup can no longer be imported from Flask due to the Jinja2 changes in Flask 3.0. I plan to fix this by updating the import path to reflect the new changes in Flask. Please assign this issue to me, and let me know if there are any additional details I should be aware of. Thanks!
